#! /bin/sh

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config borderless_monocle false

bspc config window_gap 10
bspc config split_ratio 0.50
bspc config gapless_monocle true
bspc config focus_follows_pointer true

export QT_QPA_PLATFORMTHEME=qt5ct

#some application workspace rules
bspc rule -a "/usr/bin/spotify" desktop=^5 follow=off
bspc rule -a "/usr/bin/zapzap" desktop=^4 follow=off
bspc rule -a "/usr/bin/thunderbird" desktop=^3 follow=off

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output eDP --mode 1920x1080 --left-of HDMI-A-0 --rotate normal --output HDMI-A-0 --mode 2560x1080 --rotate normal --primary
    # Workspaces
    bspc monitor HDMI-A-0 -d 6 7 8 9 10
    thunderbird &
fi
#bspc config focused_border_color "#BF616A"
#bspc config normal_border_color "#353b45"

# autostart up applications
numlockx &
sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &
~/.config/polybar/launch.sh &
dunst &
picom &
feh --bg-fill ~/Pictures/wall/neon.png &
xrdb merge ~/.Xresources &
rclone mount OneDrive\ UEx: ~/OneDrive --vfs-cache-mode writes &
setxkbmap es
