#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate-normal 
    xrandr --output HDMI-A-0 --mode 1280x1024 --rotate normal --left-of eDP
    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor HDMI-A-0 -d 6 7 8 9 0
else
    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 50

bspc rule -a Zathura desktop=^5 follow=true style=tiled
bspc rule -a Gxmessage state=floating

xinput set-prop "ELAN1200:00 04F3:30BA Touchpad" "libinput Tapping Enabled" 1

numlockx &
brightnessctl set 255
picom --experimental-backends &
~/.config/polybar/launch.sh &
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

if [[ $(/usr/bin/cat /home/alvaro/.config/polybar/launch.sh | grep 'polybar -q main') ]]; then
    feh --bg-fill /home/alvaro/.config/fondos/Desk.png
else
    feh --bg-fill /home/alvaro/.config/fondos/Tree.png
fi
