exec-once = waybar &
exec-once = rclone mount Onedrive\ UEx:  ~/OneDrive --vfs-cache-mode writes &

# i think 🤔🤔
exec-once = /usr/lib/polkit-kde/polkit-kde-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --all
