exec-once = waybar &
exec-once = rclone serve webdav Onedrive\ UEx: --addr 127.0.0.1:6969 --vfs-cache-mode writes --vv &

# i think 🤔🤔
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --all
